# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiCode.ui',
# licensing of 'GuiCode.ui' applies.
#
# Created: Thu Jul  4 12:53:16 2019
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 635)
        MainWindow.setStyleSheet("#horizontalSlider{\n"
"     background: red;\n"
"      padding: 1px;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #ccc;\n"
"    \n"
" }\n"
"#horizontalSlider_2{\n"
"     background: Green;\n"
"      padding: 1px;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #ccc;\n"
" }\n"
"#horizontalSlider_3{\n"
"     background: Blue;\n"
"      padding: 1px;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #ccc;\n"
" }\n"
"\n"
"#horizontalSlider_4{\n"
"     background: white;\n"
"      padding: 1px;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #ccc;\n"
" }\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonAddPeriod = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAddPeriod.setGeometry(QtCore.QRect(650, 170, 91, 31))
        self.buttonAddPeriod.setObjectName("buttonAddPeriod")
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStart.setGeometry(QtCore.QRect(690, 560, 111, 31))
        self.buttonStart.setAutoDefault(False)
        self.buttonStart.setDefault(False)
        self.buttonStart.setFlat(False)
        self.buttonStart.setObjectName("buttonStart")
        self.buttonSave = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSave.setGeometry(QtCore.QRect(320, 400, 91, 31))
        self.buttonSave.setObjectName("buttonSave")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 210, 801, 181))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.verticalHeader().setVisible(True)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 480, 801, 71))
        self.graphicsView.setObjectName("graphicsView")
        self.buttonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLoad.setGeometry(QtCore.QRect(210, 400, 91, 31))
        self.buttonLoad.setObjectName("buttonLoad")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(520, 0, 221, 71))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(60, 30, 41, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(110, 30, 51, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setGeometry(QtCore.QRect(160, 30, 41, 21))
        self.radioButton_6.setObjectName("radioButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 450, 191, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.buttonDel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDel.setGeometry(QtCore.QRect(10, 400, 181, 31))
        self.buttonDel.setObjectName("buttonDel")
        self.buttonStop = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStop.setEnabled(False)
        self.buttonStop.setGeometry(QtCore.QRect(540, 560, 111, 31))
        self.buttonStop.setObjectName("buttonStop")
        self.buttonSim = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSim.setGeometry(QtCore.QRect(10, 560, 91, 31))
        self.buttonSim.setObjectName("buttonSim")
        self.buttonUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUpdate.setGeometry(QtCore.QRect(540, 170, 91, 31))
        self.buttonUpdate.setObjectName("buttonUpdate")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(610, 80, 51, 21))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(670, 80, 41, 21))
        self.label_13.setObjectName("label_13")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(530, 80, 81, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(530, 100, 61, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.spinBox_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_5.setGeometry(QtCore.QRect(660, 120, 71, 21))
        self.spinBox_5.setMaximum(100000000)
        self.spinBox_5.setProperty("value", 1000)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_6.setGeometry(QtCore.QRect(660, 140, 71, 21))
        self.spinBox_6.setMaximum(1000000000)
        self.spinBox_6.setProperty("value", 100)
        self.spinBox_6.setObjectName("spinBox_6")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(560, 120, 91, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(560, 140, 101, 21))
        self.label_15.setObjectName("label_15")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(520, 80, 221, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(300, 20, 211, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 191, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.gridLayoutWidget_2)
        self.timeEdit_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.timeEdit_2.setDisplayFormat("HH:mm")
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_2.addWidget(self.timeEdit_2, 3, 1, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_2.addWidget(self.dateTimeEdit_2, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setMargin(5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setMargin(5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.gridLayoutWidget_2)
        self.timeEdit.setDisplayFormat("HH:mm")
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setMargin(5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(30, 0))
        self.dateTimeEdit.setDate(QtCore.QDate(1999, 1, 1))
        self.dateTimeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7999, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setMargin(5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 20, 281, 171))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 261, 168))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_3.setMaximum(255)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout.addWidget(self.horizontalSlider_3, 7, 5, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider.setEnabled(True)
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 3, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setMargin(5)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setMargin(5)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 4, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_2.setMaximum(255)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 5, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 5, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 5, 7, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 8, 7, 1, 1)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_4.setMaximum(255)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.gridLayout.addWidget(self.horizontalSlider_4, 8, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setMargin(5)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 4, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_3.setMaximum(255)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 7, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setMargin(5)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 4, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 3, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(120, 0, 58, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(370, 0, 58, 16))
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 21))
        self.menubar.setObjectName("menubar")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_new_incubator = QtWidgets.QAction(MainWindow)
        self.actionAdd_new_incubator.setObjectName("actionAdd_new_incubator")
        self.menuPreferences.addAction(self.actionAdd_new_incubator)
        self.menubar.addAction(self.menuPreferences.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL("valueChanged(int)"), self.spinBox.setValue)
        QtCore.QObject.connect(self.horizontalSlider_2, QtCore.SIGNAL("valueChanged(int)"), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider.setValue)
        QtCore.QObject.connect(self.horizontalSlider_3, QtCore.SIGNAL("valueChanged(int)"), self.spinBox_3.setValue)
        QtCore.QObject.connect(self.horizontalSlider_4, QtCore.SIGNAL("valueChanged(int)"), self.spinBox_4.setValue)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider_2.setValue)
        QtCore.QObject.connect(self.spinBox_3, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider_3.setValue)
        QtCore.QObject.connect(self.spinBox_4, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider_4.setValue)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL("clicked()"), self.timeEdit.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL("clicked()"), self.timeEdit_2.hide)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("clicked()"), self.timeEdit.hide)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("clicked()"), self.timeEdit_2.hide)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL("clicked()"), self.timeEdit.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL("clicked()"), self.timeEdit_2.show)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL("clicked()"), self.label_6.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL("clicked()"), self.label_7.hide)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL("clicked()"), self.label_6.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL("clicked()"), self.label_7.show)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("clicked()"), self.label_6.hide)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("clicked()"), self.label_7.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.buttonAddPeriod.setText(QtWidgets.QApplication.translate("MainWindow", "Add Period", None, -1))
        self.buttonStart.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.buttonSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.buttonLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Condition", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "&LD", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "LL", None, -1))
        self.radioButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "DD", None, -1))
        self.radioButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "LM", None, -1))
        self.buttonDel.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Selected Periods", None, -1))
        self.buttonStop.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.buttonSim.setText(QtWidgets.QApplication.translate("MainWindow", "Simulate", None, -1))
        self.buttonUpdate.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Hours ", None, -1))
        self.radioButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "Rampin&g:", None, -1))
        self.radioButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "P&ulse", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Frecuency (ms)", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Pulse width (ms)", None, -1))
        self.dateTimeEdit_2.setDisplayFormat(QtWidgets.QApplication.translate("MainWindow", "dd/MM/yy", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Switch On", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Switch Off", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "End Day", None, -1))
        self.dateTimeEdit.setDisplayFormat(QtWidgets.QApplication.translate("MainWindow", "dd/MM/yy", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Start Day", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Green", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Blue", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Intensity", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Colour", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "White", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Set Value", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Red", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Lights", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Time", None, -1))
        self.menuPreferences.setTitle(QtWidgets.QApplication.translate("MainWindow", "A&dd", None, -1))
        self.actionAdd_new_incubator.setText(QtWidgets.QApplication.translate("MainWindow", "&Add new incubator", None, -1))

