# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pt_led_controller/GuiCode.ui'
#
# Created: Tue May  5 18:21:58 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 604)
        MainWindow.setStyleSheet("#horizontalSlider{\n"
"     background: red;\n"
"     margin: 0px 2px 2px 2px;\n"
"    border-radius: 8px;\n"
"    border: 1px solid;\n"
"    \n"
" }\n"
"#horizontalSlider_2{\n"
"     background: Green;\n"
"     margin: 0px 2px 2px 2px;\n"
"    border-radius: 8px;\n"
"    border: 1px solid;\n"
" }\n"
"#horizontalSlider_3{\n"
"     background: Blue;\n"
"     margin: 0px 2px 2px 2px;\n"
"    border-radius: 8px;\n"
"    border: 1px solid;\n"
" }\n"
"\n"
"#horizontalSlider_4{\n"
"     background: white;\n"
"     margin: 0px 2px 2px 2px;\n"
"    border-radius: 8px;\n"
"    border: 1px solid;\n"
" }\n"
"\n"
"")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 20, 261, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSlider_2 = QtGui.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_2.setMaximum(255)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 5, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 4, 1, 1)
        self.horizontalSlider_4 = QtGui.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_4.setMaximum(255)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.gridLayout.addWidget(self.horizontalSlider_4, 8, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 3, 7, 1, 1)
        self.horizontalSlider_3 = QtGui.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_3.setMaximum(255)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout.addWidget(self.horizontalSlider_3, 7, 5, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 5, 7, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox_3.setMaximum(255)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 7, 7, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 8, 7, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 7, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 5, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 3, 5, 1, 1)
        self.buttonAddPeriod = QtGui.QPushButton(self.centralwidget)
        self.buttonAddPeriod.setGeometry(QtCore.QRect(660, 150, 91, 31))
        self.buttonAddPeriod.setObjectName("buttonAddPeriod")
        self.buttonStart = QtGui.QPushButton(self.centralwidget)
        self.buttonStart.setGeometry(QtCore.QRect(650, 510, 111, 31))
        self.buttonStart.setAutoDefault(False)
        self.buttonStart.setDefault(False)
        self.buttonStart.setFlat(False)
        self.buttonStart.setObjectName("buttonStart")
        self.buttonSave = QtGui.QPushButton(self.centralwidget)
        self.buttonSave.setGeometry(QtCore.QRect(670, 390, 91, 31))
        self.buttonSave.setObjectName("buttonSave")
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 190, 781, 191))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.verticalHeader().setVisible(True)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 430, 781, 71))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(310, 20, 191, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(30, 0))
        self.dateTimeEdit.setDate(QtCore.QDate(1999, 1, 1))
        self.dateTimeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7999, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_2.addWidget(self.dateTimeEdit_2, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.timeEdit_2 = QtGui.QTimeEdit(self.gridLayoutWidget_2)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_2.addWidget(self.timeEdit_2, 3, 1, 1, 1)
        self.timeEdit = QtGui.QTimeEdit(self.gridLayoutWidget_2)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.buttonLoad = QtGui.QPushButton(self.centralwidget)
        self.buttonLoad.setGeometry(QtCore.QRect(540, 390, 91, 31))
        self.buttonLoad.setObjectName("buttonLoad")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(530, 10, 161, 41))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(0, 10, 71, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 10, 51, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(100, 10, 51, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 410, 191, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.buttonDel = QtGui.QPushButton(self.centralwidget)
        self.buttonDel.setGeometry(QtCore.QRect(10, 390, 181, 31))
        self.buttonDel.setObjectName("buttonDel")
        self.buttonStop = QtGui.QPushButton(self.centralwidget)
        self.buttonStop.setEnabled(False)
        self.buttonStop.setGeometry(QtCore.QRect(530, 510, 111, 31))
        self.buttonStop.setObjectName("buttonStop")
        self.buttonSim = QtGui.QPushButton(self.centralwidget)
        self.buttonSim.setGeometry(QtCore.QRect(10, 510, 91, 31))
        self.buttonSim.setObjectName("buttonSim")
        self.buttonUpdate = QtGui.QPushButton(self.centralwidget)
        self.buttonUpdate.setGeometry(QtCore.QRect(560, 150, 91, 31))
        self.buttonUpdate.setObjectName("buttonUpdate")
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(620, 50, 51, 21))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(680, 50, 41, 21))
        self.label_13.setObjectName("label_13")
        self.radioButton_4 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(530, 50, 81, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(530, 80, 61, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.spinBox_5 = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_5.setGeometry(QtCore.QRect(670, 100, 71, 21))
        self.spinBox_5.setMaximum(100000000)
        self.spinBox_5.setProperty("value", 1000)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_6.setGeometry(QtCore.QRect(670, 120, 71, 21))
        self.spinBox_6.setMaximum(1000000000)
        self.spinBox_6.setProperty("value", 100)
        self.spinBox_6.setObjectName("spinBox_6")
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(560, 100, 91, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(560, 120, 101, 21))
        self.label_15.setObjectName("label_15")
        self.radioButton_6 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(680, 20, 51, 21))
        self.radioButton_6.setObjectName("radioButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        self.menuPreferences = QtGui.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_new_incubator = QtGui.QAction(MainWindow)
        self.actionAdd_new_incubator.setObjectName("actionAdd_new_incubator")
        self.menuPreferences.addAction(self.actionAdd_new_incubator)
        self.menubar.addAction(self.menuPreferences.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL("valueChanged(int)"), self.spinBox.setValue)
        QtCore.QObject.connect(self.horizontalSlider_2, QtCore.SIGNAL("valueChanged(int)"), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider.setValue)
        QtCore.QObject.connect(self.horizontalSlider_3, QtCore.SIGNAL("valueChanged(int)"), self.spinBox_3.setValue)
        QtCore.QObject.connect(self.horizontalSlider_4, QtCore.SIGNAL("valueChanged(int)"), self.spinBox_4.setValue)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider_2.setValue)
        QtCore.QObject.connect(self.spinBox_3, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider_3.setValue)
        QtCore.QObject.connect(self.spinBox_4, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider_4.setValue)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL("clicked()"), self.timeEdit.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL("clicked()"), self.timeEdit_2.hide)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("clicked()"), self.timeEdit.hide)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("clicked()"), self.timeEdit_2.hide)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL("clicked()"), self.timeEdit.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL("clicked()"), self.timeEdit_2.show)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL("clicked()"), self.label_6.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL("clicked()"), self.label_7.hide)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL("clicked()"), self.label_6.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL("clicked()"), self.label_7.show)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("clicked()"), self.label_6.hide)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("clicked()"), self.label_7.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Set Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Intensity", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddPeriod.setText(QtGui.QApplication.translate("MainWindow", "Add Period", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.dateTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yy", None, QtGui.QApplication.UnicodeUTF8))
        self.dateTimeEdit_2.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Switch On", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Switch Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "End Day", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Start Day", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "&LD", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "LL", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "DD", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDel.setText(QtGui.QApplication.translate("MainWindow", "Delete Selected Periods", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSim.setText(QtGui.QApplication.translate("MainWindow", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Hours ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "Rampin&g:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "P&ulse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Frecuency (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Pulse width (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("MainWindow", "LM", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPreferences.setTitle(QtGui.QApplication.translate("MainWindow", "A&dd", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_new_incubator.setText(QtGui.QApplication.translate("MainWindow", "&Add new incubator", None, QtGui.QApplication.UnicodeUTF8))

